---

- name: Remove previous values
  lineinfile:
    dest: /etc/environment
    regexp: '^{{ item.key }}'
    state: absent
  with_dict: environment_config

- name: Configuring environment
  lineinfile:
    dest: /etc/environment
    line: '{{ item.key }}="{{ item.value }}"'
  with_dict: environment_config
